let exampleCourseObject = [
   
    {
        title:"cs_system",
        core:[
            {
                course_title:"CS",
                course_number:"6304"
            },
            {
                course_title:"CS",
                course_number:"6363"
            },
            {
                course_title:"CS",
                course_number:"6378"
            },
            {
                course_title:"CS",
                course_number:"6396"
            }
        ],
        partial_core_number:1,
        partial_core:[
            {
                course_title:"CS",
                course_number:"6349"
            },
            {
                course_title:"CS",
                course_number:"6376"
            },
            {
                course_title:"CS",
                course_number:"6380"
            },
            {
                course_title:"CS",
                course_number:"6397"
            }
        ]
    },
    {
        title:"cs_network",
        partial_core_number:0,
        core:[
            {
                course_title:"CS",
                course_number:"6352"
            },
            {
                course_title:"CS",
                course_number:"6363"
            },
            {
                course_title:"CS",
                course_number:"6378"
            },
            {
                course_title:"CS",
                course_number:"6385"
            },
            {
                course_title:"CS",
                course_number:"6390"
            }
        ],
        partial_core:[]
    },
    {
        title:"cs_interactive_computing",
        core:[
            {
                course_title:"CS",
                course_number:"6326"
            },
            {
                course_title:"CS",
                course_number:"6363"
            },
            
        ],
        partial_core_number:3,
        partial_core:[
            {
                course_title:"CS",
                course_number:"6323"
            },
            {
                course_title:"CS",
                course_number:"6328"
            },
            {
                course_title:"CS",
                course_number:"6331"
            },
            {
                course_title:"CS",
                course_number:"6334"
            },
            {
                course_title:"CS",
                course_number:"6366"
            }
        ]
    },
    {
        title:"cs_intelligent_systems",
        core:[
            {
                course_title:"CS",
                course_number:"6320"
            },
            {
                course_title:"CS",
                course_number:"6363"
            },
            {
                course_title:"CS",
                course_number:"6364"
            },
            {
                course_title:"CS",
                course_number:"6375"
            },
            
        ],
        partial_core_number:1,
        partial_core:[
            {
                course_title:"CS",
                course_number:"6360"
            },
            {
                course_title:"CS",
                course_number:"6378"
            }
        ]
    },
    {
        title:"cs_cyber_security",
        core:[
            {
                course_title:"CS",
                course_number:"6324"
            },
            {
                course_title:"CS",
                course_number:"6363"
            },
            {
                course_title:"CS",
                course_number:"6378"
            }
            
        ],
        partial_core_number:2,
        partial_core:[
            {
                course_title:"CS",
                course_number:"6332"
            },
            {
                course_title:"CS",
                course_number:"6348"
            },
            {
                course_title:"CS",
                course_number:"6349"
            },
            {
                course_title:"CS",
                course_number:"6377"
            }
        ]
    },
    {
        title:"cs_data_science",
        core:[
            {
                course_title:"CS",
                course_number:"6313"
            },
            {
                course_title:"CS",
                course_number:"6350"
            },
            {
                course_title:"CS",
                course_number:"6363"
            },
            {
                course_title:"CS",
                course_number:"6375"
            }
            
        ],
        partial_core_number:1,
        partial_core:[
            {
                course_title:"CS",
                course_number:"6301"
            },
            {
                course_title:"CS",
                course_number:"6320"
            },
            {
                course_title:"CS",
                course_number:"6327"
            },
            {
                course_title:"CS",
                course_number:"6347"
            },
            {
                course_title:"CS",
                course_number:"6360"
            }
        ]
    }
]

module.exports = exampleCourseObject
